### ISSUE TITLE
incomplete support of values

### ISSUE THREAD

**Issue by vitusb** [arshadkazmi42/json-nested-replace#24]
Hello,

maybe the supported JSON-Types are not complete.

![jnestedReplace_types](https://user-images.githubusercontent.com/83558069/232343674-a1eac22c-b34c-4671-9f3f-74a3646bd78f.jpg)

I will get errors, when using "json-nested-replace" with JSON-Data that contains values of "numbers", "true", "false" and "null" **without quotes or double-quotes** under "QuickJS"-engine. I don't have "NodeJS" here for testing, but i think the error is portable here ...

I. e. for your example i will get a **TypeError: not a function**, when using :

`const INPUT_JSON = { `
` 'name': 'json-nested-replace',`
` 'author': 'Arshad Kazmi',`
` 'data01': 500,`    <<<<<<<<<<<<< !!!
` 'data02': true,`    <<<<<<<<<<<<< !!!
` 'data03': false,`    <<<<<<<<<<<<< !!!
`  'repository': {`
`    'url': 'https://github.com/arshadkazmi42/json-nested-replace',`
`    'language': 'js'`
`  }`
`};`

Here are some screenshots from the "QuickJS"-Engine (the line above the error-message is the orig "JSON.parse(JSON.stringify());"-request without your code):

No error, when using **"strings" with quoting "" or ''**:

![jnestedReplace_noerror](https://user-images.githubusercontent.com/83558069/232343645-5e2f877f-7d02-4185-bb79-aede99582300.jpg)

Error, when using numbers, boolean and null - values:

![jnestedReplace_error](https://user-images.githubusercontent.com/83558069/232343655-b639bb2b-a791-468f-afda-e3fe723660c3.jpg)

Best regards,
 vitusb

**Comment by arshadkazmi42** [comment]
@vitusb 

Thank you for reporting the issue.

The issue has been fixed in the latest version `v1.1.0` and it is released. You can update the version in your project and try again.

**Comment by vitusb** [comment]
@arshadkazmi42

Thanx for fixing, works like a charm 😃 ...
